version: '2'

services:
  reports:
    image: 'reports:latest'
    build:
      context: ./reports
    container_name: reports
    ports:
      - 8080:8080
    environment:
      - PATIENTS_URL=http://gps:8081
      - NOTES_URL=http://rewards:8082
      
  patients:
    image: 'patients:latest'
    build:
      context: ./patients
    container_name: patients
    ports:
      - 8081:8081
    environment:
      - MYSQL_HOST=db-mysql
    depends_on:
      - db-mysql

  notes:
    image: 'notes:latest'
    build:
      context: ./notes
    container_name: notes
    ports:
      - 8082:8082
    environment:
      - MONGO_HOST=mongodb
      
  db-mysql:
    image: mysql:latest
    container_name: mysql
    ports:
        - 3306:3306
    command: --innodb --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
        MYSQL_DATABASE: project_10
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: Musapa1990..        
        
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
        - 27017:27017
    environment:
        MONGO_INITDB_DATABASE: project_10
        MONGO_INITDB_ROOT_USERNAME: <admin-user>
        MONGO_INITDB_ROOT_PASSWORD: <admin-password>

